/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alutest_9 (
    input clk,
    input rst,
    input [35:0] a,
    input [4:0] alufn,
    input [2:0] b,
    output reg [35:0] result
  );
  
  
  
  wire [5-1:0] M_adder_sum;
  reg [5-1:0] M_adder_a;
  reg [3-1:0] M_adder_b;
  reg [2-1:0] M_adder_alufn;
  adder_21 adder (
    .a(M_adder_a),
    .b(M_adder_b),
    .alufn(M_adder_alufn),
    .sum(M_adder_sum)
  );
  
  reg [35:0] a1;
  
  always @* begin
    M_adder_a = a[30+4-:5];
    M_adder_b = b;
    M_adder_alufn = alufn[0+1-:2];
    a1 = {1'h0, a[0+34-:35]};
    if (alufn[0+1-:2] == 2'h3) begin
      result = a;
    end else begin
      
      case (alufn[1+3-:4])
        default: begin
          result = a;
        end
        10'h3e8: begin
          M_adder_a = a[30+4-:5];
          if (M_adder_sum == a[25+4-:5]) begin
            result = {1'h1, a[0+34-:35]};
          end else begin
            if (a[(M_adder_sum)*1+0-:1] == 1'h1 | a[(M_adder_sum - 3'h5)*1+0-:1] == 1'h1) begin
              result = {1'h1, a[0+34-:35]};
            end else begin
              result = {1'h0, M_adder_sum, a[0+29-:30]};
            end
          end
        end
        7'h64: begin
          M_adder_a = a[25+4-:5];
          if (M_adder_sum == a[30+4-:5]) begin
            result = {1'h1, a[0+34-:35]};
          end else begin
            if (a[(M_adder_sum)*1+0-:1] == 1'h1 | a[(M_adder_sum - 3'h5)*1+0-:1] == 1'h1) begin
              result = {1'h1, a[0+34-:35]};
            end else begin
              result = {1'h0, a[30+4-:5], M_adder_sum, a[0+24-:25]};
            end
          end
        end
        4'ha: begin
          M_adder_a = a[20+4-:5];
          result = {1'h0, a[25+9-:10], M_adder_sum, a[0+19-:20]};
        end
        4'hb: begin
          if (a[(a[20+4-:5])*1+0-:1] == 1'h1) begin
            result = {1'h1, a[0+34-:35]};
          end else begin
            a1[(a[20+4-:5])*1+0-:1] = 1'h1;
            result = a1;
          end
        end
      endcase
    end
  end
endmodule
