/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     WIDTH = 36
*/
module pos_8 (
    input clk,
    input en,
    input rst,
    input [35:0] data,
    output reg [35:0] out,
    output reg debug
  );
  
  localparam WIDTH = 6'h24;
  
  
  reg debugg;
  
  reg [35:0] M_regs_d, M_regs_q = 36'h0ac000000;
  
  reg [0:0] M_debug1_d, M_debug1_q = 1'h0;
  
  always @* begin
    M_debug1_d = M_debug1_q;
    M_regs_d = M_regs_q;
    
    if (en == 1'h1) begin
      M_regs_d = data;
      if (M_debug1_q == 1'h0) begin
        M_debug1_d = 1'h1;
      end else begin
        M_debug1_d = 1'h0;
      end
    end else begin
      M_regs_d = M_regs_q;
    end
    out = M_regs_q;
    debug = M_debug1_q;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_debug1_q <= 1'h0;
    end else begin
      M_debug1_q <= M_debug1_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_regs_q <= 36'h0ac000000;
    end else begin
      M_regs_q <= M_regs_d;
    end
  end
  
endmodule
