/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module wallcol_9 (
    input [4:0] pos,
    input clk,
    input rst,
    output reg [4:0] out
  );
  
  
  
  always @* begin
    out = pos - (3'h4 * (pos / 3'h4));
  end
endmodule
