/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_21 (
    input [4:0] a,
    input [2:0] b,
    input [1:0] alufn,
    output reg [4:0] sum
  );
  
  
  
  always @* begin
    sum = a;
    
    case (alufn)
      1'h0: begin
        sum = a + b;
      end
      1'h1: begin
        sum = a - b;
      end
    endcase
  end
endmodule
