/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module counter1_4 (
    input clk,
    input rst,
    output reg [1:0] out
  );
  
  
  
  reg [1:0] M_counter_d, M_counter_q = 1'h0;
  
  always @* begin
    M_counter_d = M_counter_q;
    
    out = M_counter_q;
    if (M_counter_q == 2'h2) begin
      M_counter_d = 1'h0;
    end else begin
      M_counter_d = M_counter_q + 1'h1;
    end
  end
  
  always @(posedge clk) begin
    M_counter_q <= M_counter_d;
  end
  
endmodule
