/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module wallcounter_6 (
    input clk,
    input rst,
    output reg [4:0] out
  );
  
  
  
  reg [5:0] M_wallcounter_d, M_wallcounter_q = 1'h0;
  
  always @* begin
    M_wallcounter_d = M_wallcounter_q;
    
    if (M_wallcounter_q / 2'h3 == 5'h14) begin
      M_wallcounter_d = 1'h0;
    end else begin
      M_wallcounter_d = M_wallcounter_q + 1'h1;
    end
    out = M_wallcounter_q / 2'h3;
  end
  
  always @(posedge clk) begin
    M_wallcounter_q <= M_wallcounter_d;
  end
  
endmodule
